Added Visibilty toggle for Rooms to home screen.
AOSSIE-Org/Resonate pull request #100
Opened 2023-07-31 08:25 UTC by ShivamMenda

Attempts to solve #88, Used the Visibility Widget to check whether there are rooms in the list or not and showed the appropriate widget to do so.

2023-07-31 09:12 UTC, chandansgowda commented
@ShivamMenda Can you please a add a small screen recording of how it works?

2023-07-31 09:14 UTC, ShivamMenda commented
@chandansgowda actually there's a sample room present in the room list already. And I'm not able to delete that. I just have a screenshot on how it looks with and without rooms, if that's okay? If you could remove that sample room and its empty initially then I could show you the flow where I add my own room and then it gets refreshed.

2023-07-31 12:17 UTC, ShivamMenda commented
https://github.com/AOSSIE-Org/Resonate/assets/74780977/ac959e7f-651a-458a-9874-575684039cdc

2023-07-31 12:19 UTC, ShivamMenda commented
@chandansgowda This is the flow, If the list is Empty, it'll return true and the NoRoom Widget will get triggered, and If there's a room it'll return false and the other widget will get triggered, As shown in the video it handles both cases.

2023-08-01 01:05 UTC, chandansgowda requested changes
Great job till here @ShivamMenda 
Need few changes-
1. Add any related illustration above No rooms (same colour scheme with less opacity)
2. Lets just try changing the Refresh button theme.. like make the border and text yellow and the bg transparent ?
3. Have you checked for responsiveness of the design ?

2023-08-01 01:12 UTC, ShivamMenda commented
@chandansgowda Will make these changes and get back to you.

2023-08-01 02:52 UTC, ShivamMenda commented
@chandansgowda I've made the changes requested and checked for responsiveness also, Use Get.height so everything is responsive.

2023-08-01 02:53 UTC, ShivamMenda commented
![Simulator Screenshot - iPhone 12 - 2023-08-01 at 08 06 12](https://github.com/AOSSIE-Org/Resonate/assets/74780977/d74720cd-b250-4325-b8a0-9a5143cd66a4)

2023-08-01 07:08 UTC, Aarush-Acharya commented
This looks good

2023-08-01 07:15 UTC, ShivamMenda commented
> This looks good 

@Aarush-Acharya Thank you! Glad you liked it!

2023-08-01 07:24 UTC, chandansgowda commented
Great Job @ShivamMenda 
1. Can we have a refresh icon also inside the button ?  (make sure to keep it responsive)
2. Where did you get the illustration from? If the author has to be cited, please do so in our readme file.

2023-08-01 09:21 UTC, ShivamMenda commented
@chandansgowda Made the requested changes. The illustration is from the Website https://undraw.co/. It is completely open source and does not require any attribution. So We are good to go!

2023-08-01 09:22 UTC, ShivamMenda commented
![Simulator Screenshot - iPhone 12 - 2023-08-01 at 14 48 23](https://github.com/AOSSIE-Org/Resonate/assets/74780977/afbf0f7e-ee9d-4468-b381-b8ce55c8b594)
Here's the final result

2023-08-01 10:20 UTC, chandansgowda commented on assets/images/NoRoom.png
@ShivamMenda Please use snake case for naming files

2023-08-01 10:21 UTC, ShivamMenda commented on assets/images/NoRoom.png
Sure

2023-08-01 10:25 UTC, chandansgowda commented
Also @ShivamMenda 
From next time, make sure to use our project's commit guidelines as mentioned in the Readme file.

2023-08-01 10:28 UTC, ShivamMenda commented
@chandansgowda will be careful about it next time. Sorry.

2023-08-01 10:31 UTC, chandansgowda approved these changes
@jddeep This PR can be merged now. Please review from your end. Also please merge it as one commit as per our guidelines if possible.

2023-08-04 05:28 UTC, merged