profile icon moved to appbar and minor errors corrected
AOSSIE-Org/Resonate pull request #102
Opened 2023-07-31 09:10 UTC by asare-21

This commit fixes issue #98.

I also realised that room.tags was empty but was being accessed with [0]. I fixed it with an if stateme

2023-07-31 09:10 UTC, asare-21 commented
I also added the discussions icon to the bottom navigation bar

2023-07-31 09:14 UTC, chandansgowda commented
@asare-21 Can you please add a screen recording to demo the changes ?

2023-07-31 09:14 UTC, asare-21 commented
Okay. I will do that

2023-07-31 09:19 UTC, asare-21 commented
https://github.com/AOSSIE-Org/Resonate/assets/52238457/b04b447a-134d-4188-8dab-897b4d4e4efc

2023-08-01 01:01 UTC, chandansgowda requested changes
Greta job till now @asare-21 
Need some changes-
1. Put the profile icon to the right of the appbar
2. Refactor logout button to profile screen (not required in app bar)
3. The profile icon should have the image of the user
4. Profile screen should have a title in the appbar

2023-08-01 21:50 UTC, asare-21 commented
Done refactoring. 


https://github.com/AOSSIE-Org/Resonate/assets/52238457/8bb2571e-9ba3-458a-9136-c6b49a8ca1c5

2023-08-02 01:46 UTC, chandansgowda commented on lib/views/widgets/profile_avatar.dart
> +          builder: (controller) => CircleAvatar(
Please reduce the size of the circle avatar a bit and add a tiny amber border, explore ways to make it look even more better.

2023-08-02 04:59 UTC, asare-21 commented on lib/views/widgets/profile_avatar.dart
> +          builder: (controller) => CircleAvatar(
Noted

2023-08-02 05:08 UTC, asare-21 commented on lib/views/widgets/profile_avatar.dart
> +          builder: (controller) => CircleAvatar(
New changes pushed. Kindly have a look.

2023-08-02 05:10 UTC, asare-21 commented on lib/views/widgets/profile_avatar.dart
> +          builder: (controller) => CircleAvatar(
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-02 at 06 10 12](https://github.com/AOSSIE-Org/Resonate/assets/52238457/25976e3e-5feb-4465-abdf-ee401697ce5c)

2023-08-02 13:58 UTC, chandansgowda commented on lib/views/widgets/profile_avatar.dart
> +          builder: (controller) => CircleAvatar(
Looks good. Can we reduce its size a little bit ?

2023-08-02 21:10 UTC, asare-21 commented
I've resized the icon and corrected the latest commit message

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-02 at 22 09 29](https://github.com/AOSSIE-Org/Resonate/assets/52238457/7d3174a7-a5d2-4e42-a279-83ed5530f73e)

2023-08-02 23:44 UTC, chandansgowda commented
@asare-21 This looks good. Please resolve the merge conflicts.

2023-08-06 01:49 UTC, chandansgowda commented
Hey @asare-21 
Please update me by EOD. This PR is blocking the other work that has to be done.

2023-08-06 06:28 UTC, asare-21 commented
okay

2023-08-06 07:06 UTC, asare-21 commented
Conflicts have been resolved. Sorry for the late reply

2023-08-07 05:54 UTC, asare-21 commented
@chandansgowda, I have resolved the conflicts

2023-08-08 01:10 UTC, chandansgowda approved these changes
Great job @asare-21 
@jddeep This PR can be merged.

2023-08-08 07:51 UTC, merged