Clean UI
AOSSIE-Org/Resonate pull request #115
Opened 2023-08-12 11:51 UTC by Aarush-Acharya

To be cleaned 

- [ ] create_room_screen.dart
- [ ] discussions_screen.dart
- [ ] email_verification_screen.dart
- [X] home_screen.dart
- [X] login_screen.dart
- [ ] onboarding_screen.dart
- [X] profile_screen.dart
- [ ] room_screen.dart
- [ ] signup_screen.dart
- [ ] splash_screen.dart
- [ ] tabview_screen.dart

2023-08-16 16:36 UTC, chandansgowda commented
@Aarush-Acharya Let this PR be under draft until I get the pair chat feature ready. It will take two to three days max. Then please clean that also according to what we have done previously and then mark the PR for review.

2023-08-16 17:03 UTC, Aarush-Acharya commented
Alright understood thanks

2023-08-26 11:17 UTC, Aarush-Acharya commented
Hey @chandansgowda  I have cross-checked all the screens and everything works smoothly from my end this PR is ready for review please do look into it

2023-08-26 12:32 UTC, chandansgowda commented
@Aarush-Acharya Please give a more descriptive name for the PR

2023-08-26 12:50 UTC, chandansgowda requested changes
1. The register now button should be moved to the bottom in login screen and login button should be in the bottom in registration screen.
<img width="134" alt="Screenshot 2023-08-26 at 6 09 42 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/41890434/42c1162f-0652-4859-b761-fabf9a5e04c6">

2. Verify Email button gives this snackbar with conflicting title and response.
<img width="334" alt="Screenshot 2023-08-26 at 6 10 55 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/41890434/43f076bd-e920-44f4-8304-bc74bd1a7534">

2023-08-26 12:50 UTC, chandansgowda commented on assets/images/timmer.svg
Correct typo in file name

2023-08-26 13:22 UTC, Aarush-Acharya commented on assets/images/timmer.svg
Hey @chandansgowda implemented  the requested changes

2023-08-26 13:41 UTC, Aarush-Acharya commented
New Login Screen

<img width="1154" alt="Screenshot 2023-08-26 at 6 58 15 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/92685647/84de4f81-742a-4942-b4e0-1dbc7f8fb5dd">

New SignUp Screen

<img width="1034" alt="Screenshot 2023-08-26 at 6 59 37 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/92685647/e4b0ce75-7f60-4545-859d-83e5dc67f8ea">


New Verify Email SnackBar

![image](https://github.com/AOSSIE-Org/Resonate/assets/92685647/e769ffe9-5478-45bb-9e10-0f16c486a58e)

2023-08-28 13:55 UTC, chandansgowda approved these changes
Great job @Aarush-Acharya

2023-08-28 20:07 UTC, Aarush-Acharya commented
thanks a lot @chandansgowda ]

2023-09-03 06:55 UTC, Aarush-Acharya commented
Hey @chandansgowda please review this

2023-09-03 14:52 UTC, chandansgowda approved these changes
LGTM! 
@jddeep please review and merge.

2023-09-11 15:37 UTC, merged