docs : store listing requirements
AOSSIE-Org/Resonate pull request #127
Opened 2023-09-11 18:48 UTC by devmusiczz

- added the store description with SEO optimization and increased length.
-  I've expanded the content by emphasizing the benefits and features of the Resonate app. 
- Additionally, I've included a call-to-action (CTA) to download the app from the App Store and Google Play Store and a CTA to visit the GitHub repository for contributions. 
- These CTAs can help with app store optimization and user engagement.
- I added the cover poster of RESONATE with corrections.
- added the Play Store sample screenshots including paring screenshot.

2023-09-11 18:49 UTC, devmusiczz commented
closes #109 #110 #111

2023-09-12 01:45 UTC, chandansgowda requested changes

2023-09-12 01:45 UTC, chandansgowda commented on docs/store_listing/images/PLAYSTORE SCREENSHOTS/4.png
My email is visible in this. Can you please use a different screenshot.

2023-09-12 01:45 UTC, chandansgowda commented on docs/store_listing/images/PLAYSTORE SCREENSHOTS/2.png
The app bar seems to be congested in this image. Correct it

2023-09-12 15:38 UTC, chandansgowda requested changes

2023-09-12 15:38 UTC, chandansgowda commented on docs/store_listing/images/PLAYSTORE SCREENSHOTS/4.png
Looks Good

2023-09-12 15:38 UTC, chandansgowda commented on docs/store_listing/images/PLAYSTORE SCREENSHOTS/2.png
I think the image is stretched now.

2023-09-20 06:55 UTC, chandansgowda commented
Any updates @devmusicz ?

2023-10-02 07:10 UTC, chandansgowda requested changes
Please rename PLAYSTORE SCREENSHOTS to playstore_screenshots

2023-10-02 07:10 UTC, chandansgowda commented on docs/store_listing/description.md
The content looks generated and most of it is not related to Resonate. Please go through the PRs and modify or remove the file and take it up as a new issue.

2023-10-04 05:09 UTC, chandansgowda commented
Great Job @devmusicz 
Sorry. This PR cannot be merged under hacktoberfest since it was raised 3 weeks ago. Please feel free to work on other issues or a feature you would like to implement.

2023-10-04 05:12 UTC, merged