feat: Starting point of app with Landing screens
AOSSIE-Org/Resonate pull request #132
Opened 2023-09-16 12:49 UTC by ShivamMenda

Solves #6

2023-09-16 12:50 UTC, ShivamMenda commented
@chandansgowda There was a small forking problem so created another pull request with my changes.

2023-09-16 12:52 UTC, ShivamMenda commented
https://github.com/AOSSIE-Org/Resonate/assets/74780977/4d883e58-5523-434f-8ee9-89c511120844

2023-09-16 14:53 UTC, chandansgowda commented
@ShivamMenda Great job till here.
Can we add Resonate (text/logo) in the top left of the screens ?

2023-09-16 14:54 UTC, ShivamMenda commented
@chandansgowda yeah will try to and send you the output.

2023-09-16 15:44 UTC, ShivamMenda commented
https://github.com/AOSSIE-Org/Resonate/assets/74780977/d26b4a65-505a-4477-8ad0-dc362eefc760

2023-09-16 15:45 UTC, ShivamMenda commented
@chandansgowda Added the logo as requested.

2023-09-20 15:48 UTC, chandansgowda requested changes
One small change. Rename the preference key name used as mentioned using a single line comment on one of the file.

2023-09-20 15:48 UTC, chandansgowda commented on lib/controllers/auth_state_controller.dart
> +      bool? initScreen = prefs.getBool("initScreenShown");
Rename initScreenShown to something that explains the context better. Like landingScreenShown or newUserInfoScreenShown etc

2023-09-20 15:59 UTC, ShivamMenda commented on lib/controllers/auth_state_controller.dart
> +      bool? initScreen = prefs.getBool("initScreenShown");
Sure.

2023-09-20 16:11 UTC, ShivamMenda commented
@chandansgowda Changed the name and added a comment too.

2023-09-21 14:59 UTC, chandansgowda commented on lib/controllers/auth_state_controller.dart
> +      bool? initScreen = prefs.getBool("landingScreenShown"); // landingScreenShown is the boolean value that is used to check wether to show the user the onboarding screen or not on the first launch
initScreen should also be renamed to landingScreenShown

2023-09-21 14:59 UTC, chandansgowda commented on lib/main.dart
> +  bool? initScreen = prefs.getBool("landingScreenShown");
initScreen should also be renamed to landingScreenShown

2023-09-21 14:59 UTC, chandansgowda requested changes
@ShivamMenda Please make requested changes and test the flow once.

2023-09-21 15:00 UTC, ShivamMenda commented on lib/main.dart
> +  bool? initScreen = prefs.getBool("landingScreenShown");
Sure

2023-09-21 15:03 UTC, ShivamMenda commented on lib/controllers/auth_state_controller.dart
> +      bool? initScreen = prefs.getBool("landingScreenShown"); // landingScreenShown is the boolean value that is used to check wether to show the user the onboarding screen or not on the first launch
Sure

2023-09-22 03:01 UTC, ShivamMenda commented
@chandansgowda Renaming done. Good to merge.

2023-09-22 12:40 UTC, chandansgowda commented
Hey @ShivamMenda 
Can we use GetStorage Instead of Shared Preferences ?

2023-09-22 12:57 UTC, ShivamMenda commented
@chandansgowda will implement it

2023-09-22 14:09 UTC, ShivamMenda commented
@chandansgowda Implemented with get storage. Good to go.

2023-09-22 14:36 UTC, chandansgowda commented on lib/main.dart
> +  bool? landingScreenShown = GetStorage().read("landingScreenShown");
We don't need to check it in production right? Please remove this line and the log in the next line if not required.

2023-09-22 14:37 UTC, chandansgowda requested changes
Small Change. Please look into it.

2023-09-22 16:15 UTC, ShivamMenda commented on lib/main.dart
> +  bool? landingScreenShown = GetStorage().read("landingScreenShown");
@chandansgowda Yes you are right we don't need to check it in prod. It was not necessary, I've removed it. The flow also was tested it works correctly

2023-09-22 16:17 UTC, ShivamMenda commented
@chandansgowda Fixed it. The check was not required in prod, so I tested the flow one final time. Everything works.

2023-09-23 09:07 UTC, chandansgowda commented
Great Job @ShivamMenda 🚀

2023-09-23 09:08 UTC, merged

2023-09-23 09:13 UTC, ShivamMenda commented
@chandansgowda thank you!