feat: Added github login.
AOSSIE-Org/Resonate pull request #133
Opened 2023-09-16 18:19 UTC by ShivamMenda

Solves #125

2023-09-16 20:30 UTC, ShivamMenda commented
https://github.com/AOSSIE-Org/Resonate/assets/74780977/d9bc80d3-2c14-4fc4-88bd-c785bcb69dd4

2023-09-16 20:32 UTC, ShivamMenda commented
@chandansgowda Implemented the GitHub login. For now, I generated an Oauth app on my personal GitHub account, We can replace it later.

2023-09-17 15:42 UTC, chandansgowda requested changes

2023-09-17 15:42 UTC, chandansgowda commented on lib/views/screens/signup_screen.dart
> +                ElevatedButton(
Please refactor it to a different file under widgets. We are using the same code four times. 2 in login and 2 in signup screen.

2023-09-17 15:53 UTC, ShivamMenda commented on lib/views/screens/signup_screen.dart
> +                ElevatedButton(
Sure @chandansgowda will resolve it.

2023-09-18 05:34 UTC, ShivamMenda commented on lib/views/screens/signup_screen.dart
> +                ElevatedButton(
@chandansgowda Resolved.

2023-09-18 05:36 UTC, ShivamMenda commented
@chandansgowda Refactoring is done. We can now put up the App Id and app client from the aossie account.

2023-09-20 15:35 UTC, chandansgowda commented
@ShivamMenda Reduce the size of AOSSIE logo a bit on both screens. Coz the bottom half of the screen looks a bit clumsy.

2023-09-20 15:35 UTC, chandansgowda requested changes
@ShivamMenda Reduce the size of AOSSIE logo a bit on both screens. Coz the bottom half of the screen looks a bit clumsy.

2023-09-20 16:11 UTC, ShivamMenda commented
@chandansgowda Reduced the size.


<img src=https://github.com/AOSSIE-Org/Resonate/assets/74780977/7b7bca5c-a6e6-4f52-a6fb-e26a849ed3a8 height="50%" width="50%" />


<img src=https://github.com/AOSSIE-Org/Resonate/assets/74780977/7ec76443-912e-4be0-a706-309ccc504da1 height="50%" width="50%" />

2023-09-21 15:07 UTC, chandansgowda commented
@ShivamMenda Looks good. Check my comments on #132. I'll merge this PR once that is merged.

2023-09-21 15:13 UTC, ShivamMenda commented
> @ShivamMenda Looks good. Check my comments on #132. I'll merge this PR once that is merged.

Sure. Will resolve that. We need to change the app client id and secret on the appwrite console once merged.

2023-09-26 08:56 UTC, chandansgowda commented
I have changed the secrets on appwrite.

2023-09-26 08:57 UTC, chandansgowda commented
Great job @ShivamMenda 🚀

2023-09-26 08:57 UTC, merged