feature: auth0 integration + setup google with oauth
AOSSIE-Org/Resonate pull request #15
Opened 2023-03-20 03:26 UTC by ViAsmit

2023-03-20 03:28 UTC, ViAsmit commented
Attached Screenshots:

2023-03-20 04:11 UTC, jddeep commented
@ViAsmit Here its opening up a web view for the authentication. The idea is to have two buttons - Login with Email and Login with Google on the login screen which do the expected functionality on the app itself and not open a web view.

2023-03-20 05:27 UTC, chandansgowda commented
Also @ViAsmit adding on to what @jddeep suggested, please structure the project according to MVC design and use GetX for state management.

2023-03-21 05:47 UTC, ViAsmit commented
@jddeep pushed new changes fixing flow without webview.
One thing I am not able to pick up is login with google.

Will pickup in next PR. Currently This PR has auth0 setup with email and password flow without webview.


@chandansgowda regarding mvc architecture and getx pattern. I was thinking to create a new issue, and adding it in diffrent PR. Can you create a new issue for that.

Thank you

2023-03-21 05:50 UTC, chandansgowda commented
@jddeep As far as my research goes, we wont be able to add google signin without using webview.

2023-03-21 05:51 UTC, ViAsmit commented
@chandansgowda yeah same.. we have to use web view for that...

2023-03-21 18:03 UTC, ViAsmit commented
@jddeep @chandansgowda 
Had added commits for Getx Architecture with MVC Pattern.

Attaching Screenshots for reference:

<img width="466" alt="Screenshot 2023-03-21 at 11 33 30 PM" src="https://user-images.githubusercontent.com/55342789/226701085-f3de7b69-2f66-4cc1-be1f-f9b1cb421857.png">

2023-03-24 15:29 UTC, chandansgowda requested changes
I have suggested some changes. Also, regarding the folder structure, there is no clear division between Views and Controller is what I observed. As discussed over discord server, let's have a call and finalize the folder structure.

2023-03-24 15:29 UTC, chandansgowda commented on lib/models/user.dart
> +  final String name;
We will have to add email and displayPhoto URL too since google_sign_in gives access to those attributes.

2023-03-24 15:29 UTC, chandansgowda commented on lib/modules/authentication/signup_page.dart
> +                      backgroundImage: NetworkImage("https://avatars.githubusercontent.com/u/13849023?s=280&v=4"),
Why is this image used ? If its just as a placeholder, leave a comment with TODO tag to change it.

2023-03-24 15:29 UTC, chandansgowda commented on lib/themes/colors_theme.dart
It would be better to use Material3 so that the app colours will be generated from a Seed Colour (probably yellow or green). We have to wait till we get the design to add colours.

2023-03-24 15:29 UTC, chandansgowda commented on lib/modules/authentication/authentication_binding.dart
I don't think a separate binding is required for authentication since there is only one controller to be injected as dependency. Please correct me if I am wrong.

2023-03-25 05:04 UTC, ViAsmit commented on lib/models/user.dart
> +  final String name;
I just created this file to make a models folder. Its not for any use as of now... Auth0 already provide a userModel but we can extend that to use our model, which can extensible to both auth0 and firebase user model.... actually github removes any folder if it is empty when pushed.

2023-03-25 05:05 UTC, ViAsmit commented on lib/modules/authentication/signup_page.dart
> +                      backgroundImage: NetworkImage("https://avatars.githubusercontent.com/u/13849023?s=280&v=4"),
Its just a place holder.. we will remove that once we design our registration pages

2023-03-25 05:06 UTC, ViAsmit commented on lib/themes/colors_theme.dart
Ok

2023-03-25 05:07 UTC, ViAsmit commented on lib/modules/authentication/authentication_binding.dart
Yeah..currently we have only one binding... but lets say we can have more than on binding for any service in future.. so its better to use same semantics for all services..
Any way we can remove that if you are not confortable... or have any other thoughts

2023-03-26 07:37 UTC, chandansgowda commented on lib/models/user.dart
> +  final String name;
Okayy

2023-03-26 07:42 UTC, chandansgowda commented on lib/modules/authentication/authentication_binding.dart
I had thought of keeping it simple. But you reason also makes sense. Let it be.

2023-04-02 04:06 UTC, closed without merging