fix: Improve layout on small screens with Expanded widget
AOSSIE-Org/Resonate pull request #150
Opened 2023-10-01 04:00 UTC by 0xAdiyat

Adjusted the layout in the Signup Screen to resolve the RenderFlex overflow issue on small screens, such as the iPhone SE 3rd Gen. Added the Expanded widget to ensure that child widgets fit within the available space, preventing layout errors and improving the user experience. Also, fine-tuned widget sizes for better screen compatibility.

2023-10-01 14:00 UTC, chandansgowda commented
@0xAdiyat Please add screenshots of the screens on any two devices.

2023-10-01 14:25 UTC, 0xAdiyat commented
> Ah sry, my bad. Here you go @chandansgowda 


**Before SignUp & Login screen**

<img width="499" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/0b071855-0a91-4d7a-a001-ab969b230864">

<img width="378" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/eb7aa662-93ba-4482-8f8b-44efcf6f4c44">



**After**


<img width="1163" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/cf79c086-8d6e-400d-af00-34d31eb871f3">

<img width="1087" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/964e8c9a-7e81-49b9-9068-05e06de71064">


<img width="1221" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/dc5eb27e-dc92-438c-b1f2-8b7a98e82daf">

2023-10-02 06:41 UTC, chandansgowda requested changes
Great job @0xAdiyat 
I think we can remove the logo on the top and tweak the UI a bit to make it look better.

2023-10-02 06:42 UTC, 0xAdiyat commented
> Great job @0xAdiyat I think we can remove the logo on the top and tweak the UI a bit to make it look better.

or we can make it smaller instead???

2023-10-02 06:53 UTC, chandansgowda commented
@0xAdiyat I don't think the logo is required now. It was just put in ti fill the space during initial development of the app.

2023-10-02 06:54 UTC, 0xAdiyat commented
> @0xAdiyat I don't think the logo is required now. It was just put in ti fill the space during initial development of the app.

ah i see... okay then lemme remove it for good

2023-10-02 07:33 UTC, 0xAdiyat commented
This is how it looks right now. And yeah I have made the text "Back" and "Resonate" bold to give it a little bit of detail.

<img width="1099" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/5a575123-97cf-4e08-b0a0-7b5812c14809">


<img width="1055" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/3f5ec3b0-1137-439b-82d0-9de629e133d0">


<img width="1118" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/15dc2c30-1218-4a74-a35e-521c2a740dc2">


<img width="1100" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/1617b692-c249-40bb-91dc-c174586d859e">

2023-10-02 07:42 UTC, closed without merging