Enhancement/user security password strength checker
AOSSIE-Org/Resonate pull request #176
Opened 2023-10-08 12:07 UTC by 0xAdiyat

Enhance User Security with Password Strength Checker

Incorporated a Password Strength Checker into the application to bolster user account security. The ValidatorTile widget has been updated to display password strength indicators from left to right, ensuring a more intuitive and visually appealing representation of password strength conditions. Now, the strength containers and titles are colored correctly as conditions are met, enhancing the user experience and security.

Enhance Password Strength Indicator

Modified the PasswordStrengthIndicator widget to display a color indicator that reflects the number of password strength checks met:
- If no checks are true, it shows grey color.
- If one check is true, it displays amberRed color.
- If two checks are true, it uses yellow color.
- If all three checks are true, it shows green color.

This enhancement provides more informative and visually appealing feedback on password strength.

##Screen recording

enhances #165, closes #165

2023-10-08 16:20 UTC, chandansgowda requested changes
The bar should come to the center or span the whole width. Currently it looks odd since it floats to the left.

2023-10-08 16:22 UTC, 0xAdiyat commented
> The bar should come to the center or span the whole width. Currently it looks odd since it floats to the left.

i will fix it by tomorrow

2023-10-18 15:43 UTC, 0xAdiyat commented
<img width="841" alt="image" src="https://github.com/AOSSIE-Org/Resonate/assets/67780459/83af5d18-6a9f-4c24-832d-bdb676514a8e">

@chandansgowda  Here is the updated screenshot as per the changes which were asked

2023-10-22 14:42 UTC, chandansgowda reviewed
Why have you named a colour as amber red ?

2023-10-22 14:42 UTC, chandansgowda commented on lib/utils/colors.dart
> +  static const Color amberRedColor = Colors.red;
Why have you named this amber red ?

2023-10-22 14:58 UTC, 0xAdiyat commented on lib/utils/colors.dart
> +  static const Color amberRedColor = Colors.red;
> Why have you named this amber red ?

My apologies, at first, I did try using the amber-red color to check how it looks, and it seems I forgot to update it. 😅

2023-10-25 08:05 UTC, chandansgowda approved these changes

2023-10-25 08:05 UTC, merged