fix : Confirming before deleting or leaving the audio room
AOSSIE-Org/Resonate pull request #182
Opened 2023-10-11 06:13 UTC by AKASHANGADII

2023-10-11 07:02 UTC, chandansgowda commented
@AKASHANGADII Please add a screen recording of the same.

2023-10-11 13:18 UTC, chandansgowda commented
@AKASHANGADII The flow seems to be wrong. Is the room getting deleted properly ??
Coz we are going back and then trying to delete it .

2023-10-15 06:59 UTC, AKASHANGADII commented
Yeah @chandansgowda I have maintained the same code flow.

2023-10-15 07:02 UTC, chandansgowda commented
Yes. But we are navigating to the previous screen before deleting the room. Might lead to some inconsistencies.

2023-10-15 14:32 UTC, AKASHANGADII commented
But I have written code to navigate only after deleting the controller.

2023-10-15 14:54 UTC, chandansgowda commented
@AKASHANGADII If I'm not wrong, I'm not able to see a circular indicator in the single room screen once the delete dialog is confirmed.

2023-10-15 14:56 UTC, AKASHANGADII commented
Okay I'll check it.

2023-10-15 16:32 UTC, AKASHANGADII commented
Hey @chandansgowda .I have added the loading indicator. Please review it.

2023-10-16 05:40 UTC, chandansgowda requested changes

2023-10-16 05:40 UTC, chandansgowda commented on lib/controllers/single_room_controller.dart
> +    Get.dialog(
Please refactor it as a widget. We might possibly use it many times.

2023-10-17 05:55 UTC, AKASHANGADII commented
@chandansgowda . I have made the changes. Please look into it.

2023-11-13 13:11 UTC, chandansgowda approved these changes

2023-11-13 13:11 UTC, chandansgowda commented
Great job @AKASHANGADII 🚀

2023-11-13 13:11 UTC, merged