Implemented Edit User Profile Feature
AOSSIE-Org/Resonate pull request #184
Opened 2023-10-11 18:31 UTC by vrundraval24

Fixes #93 

**Features:**
- Change Profile Picture - With the options of 
- Select From Camera, 
- Gallery or 
- Remove Profile Picture.
- Change User Display Name
- Change Username
- Save changes
- One dialogue box to alert the user if there are Unsaved Changes

I have also created Logic for **deleting the old username** from the database as the user **creates a new one**. So the old username can be **re-used**.

Display name and Username are properly **validated** and **username availability** is also checked.

Here's a zip file containing all the screenshots and screen recordings.
[Edit Profile - Vrund Raval.zip](https://github.com/AOSSIE-Org/Resonate/files/12873456/Edit.Profile.-.Vrund.Raval.zip)

2023-10-11 18:44 UTC, vrundraval24 commented
Hello @chandansgowda, Please review it.

2023-10-12 15:49 UTC, chandansgowda commented on lib/controllers/edit_profile_controller.dart
> +    storage = Storage(authStateController.client);
Get it from AppwriteService class.

2023-10-12 15:49 UTC, chandansgowda commented on lib/controllers/edit_profile_controller.dart
> +  bool isPfpChanged() {
Use full names

2023-10-12 15:50 UTC, chandansgowda requested changes
Small changes left. I've added comments.

2023-10-12 17:07 UTC, vrundraval24 commented
@chandansgowda I have completed all the requested changes. Please review it.

I am also attaching screenshots of the changes

![Screenshot 2023-10-12 222535](https://github.com/AOSSIE-Org/Resonate/assets/141143426/34e3ed39-7fac-4e43-bb7f-550e9d8dc606)
![Screenshot 2023-10-12 222527](https://github.com/AOSSIE-Org/Resonate/assets/141143426/f7860d49-ecca-4e1a-b8fd-5eb84f9528d2)
![Screenshot 2023-10-12 222549](https://github.com/AOSSIE-Org/Resonate/assets/141143426/118a3f11-ef51-4f88-a389-dc92181b536f)
![Screenshot 2023-10-12 222603](https://github.com/AOSSIE-Org/Resonate/assets/141143426/07d5824a-d471-4d5f-90e3-99b5fbdcc5a0)

2023-10-13 14:40 UTC, merged