Added: Check server status method added for the appwrite server before going to the home screen.
AOSSIE-Org/Resonate pull request #213
Opened 2023-11-12 05:07 UTC by xonx4l

issue-:#211

## Description

Added: Check server status method added for the appwrite server before going to the home screen.

Fixes #211

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have checked my code and corrected any misspellings

2023-11-12 15:21 UTC, chandansgowda requested changes
We will have to call this function and if it returns false, have to navigate the user to a screen where we tell the user that our server is down for some reason.

2023-11-15 16:33 UTC, xonx4l commented
@chandansgowda review as if I am going correct .

2023-11-16 16:27 UTC, chandansgowda requested changes
Th function you have written has to be called while the splash screen initialises.

2023-11-16 16:27 UTC, chandansgowda commented on lib/services/appwrite_service.dart
> +      Navigator.push(
We are using GetX for state management.

2024-05-24 11:16 UTC, Aarush-Acharya commented
Hey @xonx4l  please do the requested changes for us to merge the PR

2024-05-24 13:36 UTC, Aarush-Acharya commented
Hey @xonx4l  i believe the change required is very minor can be dealt with later on, so merging this PR

2024-05-24 13:37 UTC, merged