update : added forced app update
AOSSIE-Org/Resonate pull request #226
Opened 2023-12-26 20:40 UTC by SimardeepSingh1450

## Description

Added forced app update prompt so so as to prompt the users to force update the app when their app goes below a minimum version.

How it works ?
Conditionally render the login screen only after the minimum version check has been passed using the future-builder widget, but if check is not passed then a prompt pops up which asks the user to first update the app and then use it.

Fixes #217

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Locally tested this app on my android device and tested the new changes as well.

<img src="https://github.com/AOSSIE-Org/Resonate/assets/92221517/c1596f4e-efd6-4a74-9870-2ff57766366d"  width="300"/>

## Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules
- I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

2023-12-27 08:11 UTC, chandansgowda requested changes
Please refactor the project. This logic cannot be put inside login screen. Create a utility function or a separate controller if required.

2023-12-27 08:21 UTC, SimardeepSingh1450 commented
@chandansgowda , so should i put it at the beginning when the app just starts ?

2023-12-30 21:15 UTC, SimardeepSingh1450 commented
@chandansgowda ?

2023-12-31 10:36 UTC, chandansgowda commented
I meant, the code has to be refactored.

2024-01-01 20:55 UTC, SimardeepSingh1450 commented
@chandansgowda so you basically mean i should put the logic of minimumVersion check inside controllers or utility right ?, i am guessing that's what you mean by code refactoring, if i  am thinking right please tell ?

2024-01-01 23:11 UTC, SimardeepSingh1450 commented
@chandansgowda I have refactored the code and moved the logic to controllers, please review and merge.

2024-01-05 15:22 UTC, chandansgowda requested changes
@SimardeepSingh1450 I see that there are a lot of code quality guidelines to be met. Refer to dart's coding convention and update the PR.

2024-01-05 15:22 UTC, chandansgowda commented on lib/controllers/version_check_controller.dart
> +class VersionCheckResult {
Please name it similar to other controllers

2024-01-05 15:22 UTC, chandansgowda commented on lib/controllers/version_check_controller.dart
> +    Version version1 = Version.parse(appVersion);
name it as currentVersion

2024-01-05 15:22 UTC, chandansgowda commented on lib/controllers/version_check_controller.dart
> +    Version version2 = Version.parse(minimumAppVersion);
name it as minVersion or something relevant

2024-01-05 15:22 UTC, chandansgowda commented on lib/views/screens/login_screen.dart
> +class loginFormWidget extends StatelessWidget {
pascal case should be used

2024-01-05 17:54 UTC, SimardeepSingh1450 commented on lib/controllers/version_check_controller.dart
> +class VersionCheckResult {
This one i think is ok, since it is just a class for passing back data as a return type.

2024-01-05 17:55 UTC, SimardeepSingh1450 commented on lib/controllers/version_check_controller.dart
> +    Version version1 = Version.parse(appVersion);
named it as currentVersion

2024-01-05 17:55 UTC, SimardeepSingh1450 commented on lib/controllers/version_check_controller.dart
> +    Version version2 = Version.parse(minimumAppVersion);
named it as minVersion

2024-01-05 17:55 UTC, SimardeepSingh1450 commented on lib/views/screens/login_screen.dart
> +class loginFormWidget extends StatelessWidget {
performed pascal case in this file for widgets

2024-01-05 17:56 UTC, SimardeepSingh1450 commented
@chandansgowda made the changes please review

2024-02-28 06:22 UTC, SimardeepSingh1450 commented
@chandansgowda , sorry for the delay, but I have resolved the conflicts on the branch and can be merged now 👍

2024-05-24 11:11 UTC, Aarush-Acharya commented
Hey @SimardeepSingh1450  please do the requested changes, or explain the reason for leaving it hard coded.

Resolve the conflicts to bring the PR in a stable state will merge once required changes are made

2024-07-16 18:03 UTC, Aarush-Acharya commented
@SimardeepSingh1450 please do the requested changes,  asap and revet back please

2024-09-19 02:33 UTC, closed without merging