Fixed Anonymous text size
AOSSIE-Org/Resonate pull request #242
Opened 2024-01-07 08:01 UTC by JuanitaCathy

## Description

Initially, the "Anonymous" text did not fit into the button, so reducing the size helped fix it.

Fixes #235 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

![pairchatsolved](https://github.com/AOSSIE-Org/Resonate/assets/114871036/46897d31-88f0-460c-884c-d719f8f2705b)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

2024-01-15 15:21 UTC, chandansgowda requested changes
Can we use fitted box to make the size dynamic ?

2024-01-21 07:35 UTC, JuanitaCathy commented
> Can we use fitted box to make the size dynamic ?

The username box already uses fitted box as size can vary but the Anonymous text isn't going to change right.

2024-05-15 02:19 UTC, AyaNady17 commented
Great job @JuanitaCathy but can't we try something more responsive?

2024-05-21 11:08 UTC, vrundraval24 commented
Good work @JuanitaCathy but as Chandan suggested. Please use a Fitted Box. It will solve the issue.

![image](https://github.com/AOSSIE-Org/Resonate/assets/141143426/60ef04d8-eefe-4f34-8882-55a3f63f93b3)

2024-05-23 06:06 UTC, vrundraval24 requested changes
Good work @JuanitaCathy but as Chandan suggested. Please use a Fitted Box. It will solve the issue.

![image](https://github.com/AOSSIE-Org/Resonate/assets/141143426/60ef04d8-eefe-4f34-8882-55a3f63f93b3)

2024-05-23 15:31 UTC, JuanitaCathy commented
> Good work @JuanitaCathy but as Chandan suggested. Please use a Fitted Box. It will solve the issue.
> 
> ![image](https://private-user-images.githubusercontent.com/141143426/332401346-60ef04d8-eefe-4f34-8882-55a3f63f93b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Nzg1NDAsIm5iZiI6MTcxNjQ3ODI0MCwicGF0aCI6Ii8xNDExNDM0MjYvMzMyNDAxMzQ2LTYwZWYwNGQ4LWVlZmUtNGYzNC04ODgyLTU1YTNmNjNmOTNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxNTMwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmVmMGZhZTVkMjllYWY5YWM1MTE4YTM1NjNlOWE3Y2VhMzdiZmViYjk1MTNmOTk1ZTc5NDJmZGEyODMzNTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QqbuFmv5rv4r3ZH6N8VL0MV2yhnd6-UaUuWCaEAE9rA)

@vrundraval24 hello! yea i'll use a fitted box and update it.

2024-05-24 11:20 UTC, Aarush-Acharya commented
Hey @JuanitaCathy  please do the required changes will merge it as soon as possible

2024-07-16 18:00 UTC, Aarush-Acharya commented
Hey @JuanitaCathy the UI is gonna change entire so this would be over ridden thank you for the contribution. Wishing you best for future contributions.

2024-07-16 18:00 UTC, closed without merging