fix: prevent user credentials to persist on login screen after logout
AOSSIE-Org/Resonate pull request #261
Opened 2024-02-21 16:21 UTC by AyaNady17

## Description:
When a user logs out of the app, their credentials (such as email and password) should not persist on the login screen. Currently, after logging out, the text fields still retain the user’s information, which is undesirable.

##Solution: 
Cleared Text Field Controllers: After a successful login, I ensured that the text field controllers (for email and password) are cleared. This prevents the previous user’s credentials from being displayed when the login screen is revisited.

Fixes #260 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

 I thoroughly tested the behavior by logging in, logging out, and verifying that the text fields are empty upon returning to the login screen.

 
##Before Fix
https://github.com/AOSSIE-Org/Resonate/assets/144162711/5dcf6521-14d0-4f94-b2cc-cff0a99b7708

##After Fix 
https://github.com/AOSSIE-Org/Resonate/assets/144162711/8f1e39f9-34d5-40cd-8de9-5107999f96ed

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

2024-02-21 22:35 UTC, AyaNady17 commented
@jddeep please review my code and inform me if I have to modify anything?

2024-02-22 18:39 UTC, AyaNady17 commented
@chandansgowda please review so I can edit any comments ASAP

2024-02-24 13:00 UTC, jddeep requested changes

2024-02-24 13:00 UTC, jddeep commented on lib/controllers/authentication_controller.dart
>        }
please put the error types in constants file and use those constants.

2024-02-24 18:29 UTC, AyaNady17 commented on lib/controllers/authentication_controller.dart
>        }
@jddeep  I've modified that

2024-03-05 17:19 UTC, AyaNady17 commented on lib/controllers/authentication_controller.dart
>        }
any updates? @jddeep

2024-03-11 21:31 UTC, AyaNady17 commented
there was some conflicts and I've solved them, now the branch is ready to be merged @chandansgowda

2024-03-27 12:33 UTC, merged