[refactor] implement dotenv to hide api-keys from codebase
AOSSIE-Org/Resonate pull request #277
Opened 2024-02-26 19:52 UTC by opxdelwin

## Description

This PR will add a `.env` file to securely store these credentials. The code now retrieves them from the environment variable, keeping them hidden within the development environment.

Here's what this means:
 - Improved security: Credentials are no longer directly exposed in the code.
 - Separate testing setup: Developers can easily create their own Firebase and Appwrite projects for local testing without needing real credentials.

Fixes #273 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)
- [x] Documentation update

## How Has This Been Tested?

I haven't added unit tests as these are code refactors, moreover it doesn't look like tests have been initialized beforehand.
I'll be happy to add if required.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxx
- [ ] Tag the PR with the appropriate labels

2024-03-03 14:23 UTC, chandansgowda requested changes
Can't we just tell them to add the firebase_options.dart file instead of loading it from env file ?

2024-03-03 14:23 UTC, chandansgowda commented on docs/GETTING_STARTED.md
> +    - Set up firebase app as mentioned [here]()
Add link here

2024-03-04 06:30 UTC, opxdelwin commented on docs/GETTING_STARTED.md
> +    - Set up firebase app as mentioned [here]()
Yes will do!

2024-03-04 06:43 UTC, opxdelwin commented
As of now, API keys of the production server are exposed, which might have been unintended. This could lead to exploitation of resources and incur unexpected costs. That is why we prefer .env while initialisation of any project.

Secondly, But then, later when we're to run automation to publish releases straight to the respective platform, or run checks on PR and commits, removing this file from the codebase would raise issues.

2024-03-04 13:56 UTC, opxdelwin commented on docs/GETTING_STARTED.md
> +    - Set up firebase app as mentioned [here]()
I've updated, along with non null checks for optional parameters on `firebase_options.dart`.

2024-05-24 11:33 UTC, closed without merging

2024-05-24 11:33 UTC, Aarush-Acharya commented
Hey @opxdelwin Thanks a lot for your contribution  🚀✨,

having a .env is always considered as on of the best practices for any repository. But currenlty we planning to have a .bat script that creates an appwrite env similar to our main env on the contibutors local machine using appwrite self hosted (docker). Thus we wont have to expose our env variables anymore rather more control would be in the contributors hands.

We really appreciate your work towards Resonate. There are a lot of issues and things to be done in the app.  Lets move forward and build Resonate a beautiful app. 

Thank you