Clearing up Unused Imports and Improving Performances and using lowerCamelCase syntax where required
AOSSIE-Org/Resonate pull request #285
Opened 2024-02-29 10:44 UTC by Naman30903

## Description

Removed unused imports , added const where required.

Fixes # (issue)

No issue fixes just improving Codebase

- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)

## Checklist:

- [✓ ] My code follows the style guidelines of this project
- [✓ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [✓ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [✓ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

2024-02-29 10:47 UTC, Naman30903 reviewed
Please Review the code and suggest changes or point out the problems

2024-03-03 12:49 UTC, Naman30903 commented
@chandansgowda Please can you review my PR

2024-05-24 04:58 UTC, vrundraval24 commented
Hey, @Naman30903 Please resolve the merge conflicts.

2024-05-24 05:05 UTC, vrundraval24 requested changes
Please don't remove the **Last Comma** as it helps Dart to arrange things in better way.

2024-05-24 05:05 UTC, vrundraval24 commented on lib/utils/utils.dart
> +          horizontal: UiSizes.size_20, vertical: UiSizes.size_20),
```suggestion
          horizontal: UiSizes.size_20, 
          vertical: UiSizes.size_20,
      ),
```

2024-05-24 05:05 UTC, vrundraval24 commented on lib/utils/utils.dart
> +            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
```suggestion
            padding: const EdgeInsets.symmetric(
            horizontal: 20, 
            vertical: 10,
        ),
```

2024-05-24 11:40 UTC, Aarush-Acharya commented
Hey @Naman-30903 please do the suggested changes and resolve the conflicts to bring it into the clean state so that we can merge

2024-05-28 10:09 UTC, closed without merging