Brought Resonate to Stable State
AOSSIE-Org/Resonate pull request #329
Opened 2024-06-11 15:15 UTC by Aarush-Acharya

## Description

Brought Resonate to stable state,

- Removed print statements 
- Migrated Appwrite Plugin to 12.0.4
- Solved tag controller issue

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Refactor (does not change functionality, e.g. code style improvements, linting)

## How Has This Been Tested?

The following flows were tested 

- Login/Logout
- Email Verification
- Discussion Creation/Deletion/Conversion
- Room Creation/ Deletion
- Room mic on/off

Please include screenshots below if applicable.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2024-06-12 20:11 UTC, chandansgowda commented
Hey @vrundraval24 
please review.

2024-06-15 08:43 UTC, vrundraval24 requested changes
I cannot create New Audio Room, is this desired behavior?? the scheduled room is creating even without Date. Idk the implementation is still left or not. Or is this behavior desired. but please take a look.

and the BUG on pressing back button on Create Audio Room is also crashes app and on restart black screen appears. That need to be taken care of in priority.

2024-06-15 08:43 UTC, vrundraval24 commented on lib/controllers/discussions_controller.dart
> +          databaseId: "6522fcf27a1bbc4238df",
hey can you make these database id and collection id dynamic by storing them in some variable. is there any reason for using them directly?

2024-06-15 08:43 UTC, vrundraval24 commented on lib/views/screens/create_room_screen.dart
> +    return PopScope(
BUG HERE.
Pressing Back button on Create New Room Screen (Audio Room) Closes the whole app.

2024-07-06 11:18 UTC, chandansgowda commented
Update on this @Aarush-Acharya ?

2024-07-06 12:46 UTC, Aarush-Acharya commented
@chandansgowda will have it done by today

2024-07-06 13:14 UTC, Aarush-Acharya commented
Hey @chandansgowda  @vrundraval24  i have made the requested changes

2024-07-10 15:45 UTC, vrundraval24 approved these changes

2024-07-10 15:47 UTC, vrundraval24 commented
@chandansgowda 
Everything looks fine. 
Great job @Aarush-Acharya 🚀

2024-07-11 18:00 UTC, merged

2024-07-11 18:01 UTC, chandansgowda commented
Great job @Aarush-Acharya 🚀

2024-07-12 11:11 UTC, Aarush-Acharya commented
Thank you @chandansgowda, will have the other work done asap