[UI] Notifications Screen with mock data
AOSSIE-Org/Resonate pull request #337
Opened 2024-08-12 21:45 UTC by AyaNady17

## Description

Implemented notifications screen UI with mock data

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

tested manually 

Please include screenshots below if applicable.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist
![Screenshot_1723498365](https://github.com/user-attachments/assets/cba43ec7-6a3a-417b-921f-58513fb1ab24)

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Tag the PR with the appropriate labels

2024-09-01 18:30 UTC, AyaNady17 commented
please review @Aarush-Acharya  @vrundraval24

2024-09-14 08:10 UTC, chandansgowda requested changes
minor changes

2024-09-14 08:10 UTC, chandansgowda commented on lib/views/new_screens/new_notifications_screen.dart
> +                backgroundImage: NetworkImage(
Let's use an asset image here

2024-09-14 08:10 UTC, chandansgowda commented on lib/views/new_screens/new_notifications_screen.dart
> +class NotificationModel {
move this to models folder

2024-09-14 21:02 UTC, AyaNady17 commented on lib/views/new_screens/new_notifications_screen.dart
> +                backgroundImage: NetworkImage(
done

2024-09-14 21:03 UTC, AyaNady17 commented on lib/views/new_screens/new_notifications_screen.dart
> +class NotificationModel {
done

2024-09-18 11:38 UTC, Aarush-Acharya commented
@chandansgowda  @AyaNady17  Looks good to me

2024-10-01 18:18 UTC, AyaNady17 commented
please check this @chandansgowda

2024-10-01 21:11 UTC, merged