Ux improvements
AOSSIE-Org/Resonate pull request #36
Opened 2023-04-26 13:37 UTC by ViAsmit

Changes:
1. Global Theme Date for icons, button and text
2. form validation for login and signup
3. Onboarding Flow with Firestore and Firebase Storage for saving user custom info and profile image

https://user-images.githubusercontent.com/55342789/234592474-1d3d8b6b-9feb-4995-9738-66c510592df4.mp4

2023-05-05 16:14 UTC, jddeep requested changes

2023-05-05 16:14 UTC, jddeep commented on lib/models/resonate_user.dart
> +}
Please use retrofit or freezed package.

2023-05-07 07:28 UTC, chandansgowda commented on lib/models/resonate_user.dart
> +}
Also @ViAsmit, I feel followers/following is not required for individual users. I think its better if we make it for Organizations. What do you think @jddeep ?

2023-05-07 07:31 UTC, chandansgowda commented
Merging this PR Closes #33

2023-05-07 10:26 UTC, jddeep commented on lib/models/resonate_user.dart
> +}
Yes let's not dig too deep on user profiles this season @chandansgowda

2023-05-10 04:13 UTC, merged