feat: splash screen implemented
AOSSIE-Org/Resonate pull request #64
Opened 2023-06-21 04:12 UTC by Aarush-Acharya

closes #61 and fixes #57, fixes #58 

Resolved display of login screen for a split second while app restarts instead a splash screen is shown 

Navigated to tab view screen after onboarding 

Resolved null check on a null value in the profile screen

2023-06-22 05:13 UTC, chandansgowda requested changes
@Aarush-Acharya The app crashes if you logout of the account and restart the app. This is possibly because AuthenticationController getting exposed once the splash screen closes. Please check and make necessary fix.

2023-06-22 05:20 UTC, Aarush-Acharya commented
Understood on it

2023-06-22 06:52 UTC, Aarush-Acharya commented
@chandansgowda The fix has been integrated seems that the logic to navigate the user to the login screen after the splash screen if the user hasn't logged in was not written, it was a fault from my side apologies

2023-06-22 07:03 UTC, chandansgowda approved these changes

2023-06-22 07:04 UTC, chandansgowda commented
@Aarush-Acharya Looks good. Please share the link for the PR on our discord server also.

2023-06-22 07:05 UTC, Aarush-Acharya commented
@chandansgowda understood and thank you for reviewing the commits, the splash screen still needs the changes discussed

2023-06-22 07:42 UTC, chandansgowda commented
Okay then its better to get the redesign with all app icon assets changed.

2023-06-22 08:28 UTC, Aarush-Acharya commented
Understood doing in the same PR

2023-06-22 10:18 UTC, Aarush-Acharya commented
Hey @chandansgowda  app logo has been implemented moving on to redesign of splash screen

2023-06-22 10:19 UTC, Aarush-Acharya commented
Hey @chandansgowda  app logo has been implemented moving on to redesign of splash screen

2023-06-22 19:40 UTC, Aarush-Acharya commented
Hey @chandansgowda apologies for not confirming the redesigned UI screen prior to committing 

here it is 
https://github.com/AOSSIE-Org/Resonate/assets/92685647/b7f4f1a3-5537-4c2e-a7b7-3448efa99722

do let me know of any changes required

2023-06-23 01:38 UTC, chandansgowda commented
@Aarush-Acharya Can we increase the size of resonate logo ? I feel the splash screen still looks plain. And reduce AOSSIE logo size.

Or another option is to have apssie and resonates logo in the center as a row with a divider. Check which one looks good.

2023-06-23 09:04 UTC, Aarush-Acharya commented
@chandansgowda  thank you would do and revert asap

2023-06-23 16:27 UTC, Aarush-Acharya commented
Hey @chandansgowda  apologies for the delay

here are the two screens implemented do let me know which one to continue with 

A. Divider
https://github.com/AOSSIE-Org/Resonate/assets/92685647/405cf949-9660-4667-b836-b0162ff9ae15


B.  Refactored Original 
https://github.com/AOSSIE-Org/Resonate/assets/92685647/14e4dd57-2bc4-4e19-af66-a4581e1cc566

2023-06-23 17:04 UTC, chandansgowda commented
Divider version looks better.

2023-06-23 17:05 UTC, Aarush-Acharya commented
Understood would commit that one

2023-06-23 17:18 UTC, chandansgowda commented
@Aarush-Acharya Okayy

2023-06-23 18:05 UTC, Aarush-Acharya commented
Hey @chandansgowda I believe the work for this PR is done do let me know if anything needs to be updated would try to find some new issue to contribute to form tomorrow onwards

2023-06-25 18:44 UTC, chandansgowda requested changes

2023-06-25 18:44 UTC, chandansgowda commented on lib/main.dart
> +      initialRoute: '/splash',
Use static routename from Approute class.

2023-06-25 18:44 UTC, chandansgowda commented on lib/bindings/auth_splash_bindings.dart
> +    Get.put(SplashController());
Do we actually need to inject the controller compuslorily (put)? If yes, please explain why can't we use lazyPut.

2023-06-26 04:24 UTC, Aarush-Acharya commented on lib/main.dart
> +      initialRoute: '/splash',
Understood

2023-06-26 04:26 UTC, Aarush-Acharya commented on lib/bindings/auth_splash_bindings.dart
> +    Get.put(SplashController());
While debugging tried to switch between put and lazy put but that wasn't the problem ig, still would test with lazy put and if it works as required would use lazy put then

2023-06-26 05:37 UTC, Aarush-Acharya commented on lib/bindings/auth_splash_bindings.dart
> +    Get.put(SplashController());
Tried it out works fine

2023-06-26 05:43 UTC, Aarush-Acharya commented
@chandansgowda the changes have been implemented

2023-06-26 10:10 UTC, chandansgowda approved these changes

2023-06-26 20:47 UTC, closed without merging